/**
 * World Selfie Check Verification Service
 * Validates the zero-knowledge proof generated by World App Selfie Check against World's Relying Party API (/api/v4/verify/{rp_id}).
 */
export async function verifyWorldSelfieProof(
  proof: any,
  signal?: string,
  /** Only /api/auth/world-session, which records every session proof it accepts. */
  opts: { allowSession?: boolean } = {}
): Promise<{ success: boolean; error?: string; code?: string; nullifier?: string }> {
  const rpId = process.env.NEXT_PUBLIC_WORLD_RP_ID || "rp_62d19ed87590c550";
  const action = process.env.NEXT_PUBLIC_WORLD_ACTION || "lifeline-human-verify";

  if (!rpId) {
    return {
      success: false,
      error: "NEXT_PUBLIC_WORLD_RP_ID is not configured",
    };
  }

  try {
    console.log(`[World-Verify v4] Attempting RP verification at https://developer.world.org/api/v4/verify/${rpId}`);

    let v4Payload: any;
    if (proof.session_id) {
      // Session proofs are verified by /api/auth/world-session, which records
      // each one; anywhere else they would name a nullifier World never checked.
      if (!opts.allowSession) return { success: false, error: "Session proofs sign in through World ID sessions.", code: "session_proof" };
      // A session proof has no action, and must reach the portal as IDKit produced it.
      v4Payload = proof;
    } else if (proof.protocol_version && Array.isArray(proof.responses)) {
      // The action is Lifeline's, never the caller's.
      v4Payload = { ...proof, action };
    } else if (proof.responses && Array.isArray(proof.responses)) {
      v4Payload = {
        protocol_version: "3.0",
        nonce: proof.nonce || String(Date.now()),
        ...proof,
        action,
      };
    } else {
      v4Payload = {
        protocol_version: "3.0",
        action,
        nonce: String(Date.now()),
        responses: [
          {
            identifier: proof.verification_level || "selfie",
            nullifier: proof.nullifier_hash || proof.nullifier,
            merkle_root: proof.merkle_root,
            proof: proof.proof,
            verification_level: proof.verification_level || "selfie",
          },
        ],
      };
    }

    if (signal && !v4Payload.signal_hash) {
      v4Payload.signal_hash = signal;
    }

    const v4Response = await fetch(`https://developer.world.org/api/v4/verify/${rpId}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(v4Payload),
    });

    const v4Data = await v4Response.json();
    console.log("[World-Verify v4] API Response:", v4Response.status, JSON.stringify(v4Data));

    if (v4Response.ok && (v4Data.success === true || v4Data.results?.[0]?.success === true)) {
      // Only a nullifier World checked: its answer, or the one inside the
      // proof it just verified - never a field the caller added beside it.
      const nullifier = v4Data.nullifier || v4Data.results?.[0]?.nullifier || v4Payload.responses?.[0]?.nullifier;
      return { success: true, nullifier };
    }

    if (v4Data.results && Array.isArray(v4Data.results) && v4Data.results[0]) {
      const item = v4Data.results[0];
      if (item.success === true) {
        return {
          success: true,
          nullifier: item.nullifier || v4Data.nullifier || v4Payload.responses?.[0]?.nullifier,
        };
      }
      return {
        success: false,
        code: item.code || v4Data.code,
        error: item.detail || v4Data.detail || "Proof verification failed",
      };
    }

    if (v4Data.detail || v4Data.code) {
      return {
        success: false,
        code: v4Data.code,
        error: v4Data.detail || "Proof verification failed",
      };
    }

    return {
      success: false,
      error: "World ID proof verification failed",
    };
  } catch (v4Err: any) {
    console.error("[World-Verify v4] Network error during v4 call:", v4Err);
    return {
      success: false,
      error: v4Err.message || "Failed to communicate with World Developer API",
    };
  }
}

